spring:
  application:
    name: Tool collection
  servlet:
    multipart:
      max-file-size: 1000GB
      max-request-size: 1000GB
      enabled: true
  thymeleaf:
    cache: false
  sql:
    init:
      mode: never
report:
  jira:
    token: "Bearer "

logging:
  level:
    org.springframework.security: debug