spring:
  application:
    name: Tool collection
  datasource:
    url: jdbc:postgresql://localhost:5432/tool
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 1000GB
      max-request-size: 1000GB
      enabled: true
  thymeleaf:
    cache: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
report:
  jira:
    token: "Bearer "

logging:
  level:
    org.springframework.security: debug